package me.warriorg.sbm.anotation.department.dao;

import me.warriorg.sbm.anotation.department.domain.Department;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import java.util.List;

/**
 * generated by Generate dcits
 *
 * @author: 朱正东
 * @date: 2019-02-11
 */
@Mapper
public interface DepartmentMapper {

    @Select(value = "select * from departments")
    List<Department> find();
}
