package me.warriorg.sbm.anotation.department.domain;

import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;

/**
 * generated by Generate dcits
 *
 * @author: 朱正东
 * @date: 2019-02-11
 */
@Setter
@Getter
public class Department implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * null
     */
    private String deptNo;
    /**
     * null
     */
    private String deptName;
}
