package src.main.java.me.warriorg.sbm.xml.department.dao;

import org.apache.ibatis.annotations.Mapper;

/**
 * generated by Generate dcits
 *
 * @author: 朱正东
 * @date: 2019-02-11
 */
@Mapper
public interface DepartmentMapper {
    
}
